### ISSUE TITLE
New toolchain does not provide mips/cpu.h and related headers

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#115]
I'm currently migrating to the new custom toolchain, and I can't get it to build our sources, because it does not come with `mips/cpu.h`, and - presumably - other headers. Should we import and include such files in with sources, or is there some other way I should get the new toolchain to work?

**Comment by cahirwpz** [comment]
Yes, we should import custom header files provided by Imagination Technologies.
