### ISSUE TITLE
Usage of pool allocator can cause vmem test to fail 

### ISSUE THREAD

**Issue by mohrcore** [cahirwpz/mimiker#1208]
The problem was observed by me when working on #1153.
Feel free to close issue if upon review you find my usage of pool allocator to be flawed.

Here's the version of a _vcache_ that uses a pool allocator, before I replaced it with kmalloc due to the observed issue.
https://github.com/cahirwpz/mimiker/blob/a6b7923715627bd5e1a33915f48b092257a6a278/sys/kern/vfs_vcache.c

### Description:

Running my code that uses pool allocator results in `vmem` test failure upon sufficient number of test runs. I could not reproduce the issue, even when using the same seeds for the test as the ones that caused a failure. Sounds like a nasty race condition to me. Could it be related to #1156? The issue was gone once I dropped the pool allocator in favor of kmalloc. The `vmem` test lacks any documentation and I don't understand what's going on there.

Example logs from a failed test run:
https://github.com/cahirwpz/mimiker/runs/4928250610?check_suite_focus=true

**Comment by cahirwpz** [comment]
We hope this bug has vanished after some major improvements to memory allocation facilities, i.e. basing `kmalloc` on `pool` allocator and removing cyclic dependency around bundary tag allocations.
