### ISSUE TITLE
Basic support for user-space signals

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/mimiker#144]
It's completely unclear what needs to be implemented to have basic support for signals.

We should perform some code analysis and it will probably start from [postsig](http://bxr.su/FreeBSD/sys/kern/kern_sig.c#2776) and [sendsig](http://bxr.su/FreeBSD/sys/mips/mips/pm_machdep.c#84) routines. There're (at least) two system calls that are necessary to implement for user-space signals: [sigaction](https://www.freebsd.org/cgi/man.cgi?query=sigaction&sektion=2) and [sigreturn](https://www.freebsd.org/cgi/man.cgi?query=sigreturn&sektion=2).

**Comment by rafalcieslak** [comment]
#271 proposes an implementation.

**Comment by cahirwpz** [comment]
Implemented with #271.
