### ISSUE TITLE
Does vm_page_fault assume the lowest addr of a page is always the first to be accessed?

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#162]
I've been looking at `vm_page_fault`, and I am very confused about the way it calls `pmap_map` at the end:

```c
vm_addr_t fault_page = fault_addr & -PAGESIZE;
vm_addr_t offset = fault_page - entry->start;
vm_page_t *frame = vm_object_find_page(entry->object, offset);

if (!frame)
  frame = obj->pgr->pgr_fault(obj, fault_page, offset, fault_type);
pmap_map(map->pmap, fault_addr, fault_addr + PAGESIZE, frame->paddr,
         entry->prot);

return 0;
```
Take note of the second and third argument to `pmap_map` (`start` and `end`). I suppose the range we want to map is `fault_page, fault_page + PAGESIZE`, not `fault_addr, fault_addr + PAGESIZE`. I also see that `pmap_map` requires both addresses to be page-alligned. So in current case, if the first address accessed does not happen to be page-alligned (it happens to be in our current test-cases...), `pmap_map` will crash.

I'm sorry I'm creating these questions as issues instead of just sending a PR with a fix, but I am *genuinely* unsure about how this is intended to work, so I need a confirmation that my findings are correct before I prepare a fix.

**Comment by cahirwpz** [comment]
You're right! This needs to be fixed.
