### ISSUE TITLE
Inter-process communication with pipes

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/mimiker#245]
Pipes are unidirectional method of inter-process communication described in [pipe(2)](http://netbsd.gw.com/cgi-bin/man-cgi?pipe+2+NetBSD-current).

Pipes are another [type](http://bxr.su/NetBSD/sys/sys/file.h#161) of file with corresponding [fileops](http://bxr.su/NetBSD/sys/kern/sys_pipe.c#114) structure. [pipe](http://bxr.su/NetBSD/sys/sys/pipe.h#102) structure stores file related metadata, synchronization primitives and [pipebuf](http://bxr.su/NetBSD/sys/sys/pipe.h#63) cyclic buffer. [pipe_read](http://bxr.su/NetBSD/sys/kern/sys_pipe.c#480) and [pipe_write](http://bxr.su/NetBSD/sys/kern/sys_pipe.c#968) functions use [uiomove](http://netbsd.gw.com/cgi-bin/man-cgi?uiomove+9+NetBSD-current) facility to copy data between the buffer (placed in kernel virtual address-space) and source and destination processes.

**Comment by cahirwpz** [comment]
@MoloToha Any progress on the task? It's a pretty exciting feature so we'd like to have it sooner rather than later.

**Comment by MoloToha** [comment]
@cahirwpz I'll try my best to finish this until the next meeting. Last week I was busy with other subjects so I didn't make any progress, although the task is close to be done (you can see it on pipe branch).

**Comment by cahirwpz** [comment]
Could you prepare a PR with [WIP](https://github.com/cahirwpz/mimiker/wiki/Github-issue-PR-labels) label so we could have a look at it?

**Comment by cahirwpz** [comment]
Implemented in c9068b7b69bf71f5f4fa0563e6a56f4880f13389
