### ISSUE TITLE
Process structure

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#278]
We've decided this is a good moment to start grouping threads into processes.

**Comment by rafalcieslak** [comment]
I've proposed a solution in #285.

**Comment by cahirwpz** [comment]
@rafalcieslak Please move `td_uspace` and `td_fdtable` to process structure, before you continue your work on #271.

**Comment by rafalcieslak** [comment]
Resolved with #289 and #290.
