### ISSUE TITLE
Cirrus Logic GD5446 driver

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#286]
We do have a VGA driver ready, but it only supports the QEMU `stdvga` device. OVPsim does not provide any device like that one, the only VGA available for OVPsim is a Cirrus Logic GD5445. We'll need to implement support for it as a separate driver, with significantly different logic than the `stdvga` driver (it won't be able to use neither *VBE* nor *Bochs extensions*, and will have to use ISA ioports, as support for MMIO via BAR2 is not implemented). The new driver should conform to the `./include/vga.h` interface.

**Comment by cahirwpz** [comment]
Closed because we're going to drop OVPsim in favor of QEMU.
