### ISSUE TITLE
`do_lseek` ignores `whence` argument

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#287]
The third argument to `lseek` is `whence`, which may be one of:

 - `SEEK_SET` - the file offset is set to `offset` bytes
 - `SEEK_CUR` - the file offset is set to its current location plus `offset` bytes
 - `SEEK_END` - the file offset is set to the size of the file plus `offset` bytes.

Currently our `do_lseek` ignores `whence` and always works as `SEEK_SET` (it was fine for the programs we've tested until now), but we'll have to implement other flags as well. `SEEK_CUR` is trivial to implement, `SEEK_END` *probably* requires the underlying file to support `getattrs`.

**Comment by coodie** [comment]
I have noticed that already. I plan to work on mimiker upcoming weekend and hope to provide this feature.

**Comment by cahirwpz** [comment]
@coodie What is the status of this task? Paweł Dyniec (@dyniec) expressed an interest in fixing the bug.

**Comment by coodie** [comment]
@cahirwpz
That's easy to fix, and the main difficulty is going to be integration of user space library with our kernel, that's gonig to be quite tedious and if @dyniec really wants to fix it, let him do it (for extra points!).

**Comment by cahirwpz** [comment]
The Open Group Base Specifications Issue 7: [lseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/lseek.html)

**Comment by cahirwpz** [comment]
Implemented with #358
