### ISSUE TITLE
PCI-ISA bridge driver

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#292]
We urgently need a very simple driver for the PCI-ISA bridge, so that we may access the ISA bus and start writing drivers for devices on the ISA bus. The bridge driver itself won't have much to do, at the moment all it has to do is claiming the PCI device, and preparing the ISA bus. Later it will also be responsible for dispatching probe/attach requests to ISA drivers.

**Comment by cahirwpz** [comment]
Obsoleted by #380.
