### ISSUE TITLE
sysinit

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#294]
We have a lot of components in `sys/*c.` that want to prepare something during kernel startup. We've gathered such initializer functions in `kernel_init(...)`, which contains a long list of various `init` functions. The order in which these functions are called is significant, for example `vga_init` assumes the `vfs_init` has already completed. Such dependencies make it difficult to manage the contents `kernel_init()`. We would like to have an uniform interface for registering such initializer functions and specifying their dependencies. A `*.c` submode that needs a function to be called at kernel init would contain a directive similar to this (example for `vfs`):

```c
SYSINIT_ADD("vfs", vfs_init, {"vnode", "ramdisk", NULL});
```

This macro would create an instance of `sysinit_entry_t` filling it with data, and would store a pointer that instance into a linker set of all sysinit entries. No `vfs`-related function calls would need to be added to `kernel_init`.

Then, during `kernel_init()` we would read all sysinit entries gathered by the linker set, perform [topological ordering](https://en.wikipedia.org/wiki/Topological_sorting), and call the requested functions one by one. The ordering will ensure that all dependencies between subsystems are met.

Implementing this interface would help us manage the startup procedure a lot. This mechanism would be mildly similar to freebsd's [sysinit](https://www.freebsd.org/cgi/man.cgi?query=SYSINIT&sektion=9).

This task doesn't require much research or interaction with hardware/platform, and I believe it should be fun. The only potentially complex part is implementing the ordering. If any of you guys is interested, go ahead and assign yourself.

**Comment by cahirwpz** [comment]
Closed by #315
