### ISSUE TITLE
Add DEBUG and RELEASE build

### ISSUE THREAD

**Issue by coodie** [cahirwpz/mimiker#312]
Kernel built in DEBUG mode would be slower but would have more debugging support (like -O0 flag), more logging etc.

Kernel built in RELEASE mode would be simply the one we'd like to release. This means it's going to be compiled with high optimization features and all unnecessary logging stuff removed.

There are two reasons I think this would be great to introduce it in nearby future. Our kernel starts to have more and more features which would make a good presentation (like mandelbrot), but it has a lot of unnecessary logging (there is probably other solution to solve this problem), and recently we've run into issues with different kernel behaviour on different optimization levels. We'd like to make sure our kernel works fine on every optimization level to spot possible implementation mistakes.

This task would probably take a lot of work, here is brief outline of what this task should cover:
- Refactor our build system to emit dependencies each time we change between DEBUG and RELEASE modes. This might need to add ./configure script.
- See where there is too much logging for RELEASE build and surround it with proper defines.
- Improve CI to run in debug and release

**Comment by cahirwpz** [comment]
This proposal has not proven to be of great value throught the last semester. Nobody had a feeling this is what needs to be done to improve quality of work environment. There're other methods of limiting kernel verboseness, for instance `klog-quiet` or `klog-mask` parameters. For now, it seems much more desired feature would be to split kernel output and user-space output into two windows, with a possibility to save them to a file.
