### ISSUE TITLE
Kernel threads

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/mimiker#33]
For reference look at [proc.h](http://bxr.su/FreeBSD/sys/sys/proc.h#204). Thread structure has been already defined in [thread.h](https://github.com/cahirwpz/mimiker/blob/master/include/thread.h). Thread handling functions are implemented in [kern_thread.c](http://bxr.su/FreeBSD/sys/kern/kern_thread.c).

``` c
thread_t *thread_create(const char *name, void (*fn)());
void thread_exit() __attribute__((noreturn));
void thread_destroy(thread_t *);
int thread_join(thread_t *);
```

**Comment by cahirwpz** [comment]
First working version should allocate `thread_t` structure using `kmalloc` and stack using `vm_phys_alloc`. I expect two threads to print out, using serial port, an identifier letter and be switched every 10ms. After several second they should call `thread_exit` and main thread should continue after it `thread_join`'ed both child threads. Early locking mechanism may be necessary to handle aforementioned functionality.

Moreover, first path of execution (i.e. one that enters `kernel_main`) has to be converted to a thread. That will require stack switching mechanism.

**Comment by cahirwpz** [comment]
This is almost ready to be closed. We need #185 to be completed.

**Comment by rafalcieslak** [comment]
I'll reapply #185 onto master updating it to current interface, fix synchronization, and create a new PR.
