### ISSUE TITLE
sbrk does not work in forked processes

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#332]
If a process calls `fork` without using `sbrk` previously, then the child process will not be able to `sbrk` as it is missing an `sbrk_entry` in its user `vm_map`. This is a bug in `vm_map_clone`, does not set new map's `sbrk_entry` to the equivalent of `sbrk_entry` in the original map.

**Comment by cahirwpz** [comment]
IIUC d2b02725790d8ec454d7268c198750343b5b86bc fixed the problem.
