### ISSUE TITLE
vfs_lookup improvements

### ISSUE THREAD

**Issue by coodie** [cahirwpz/mimiker#355]
With recent work on vfs subsystem I realised this might be time to improve vfs_lookup we have. Possible improvements are:

- Make vfs_lookup work with parent directories: ".."
- Make vfs_lookup support relative paths
- Add normalize function, to make paths as simple as possible:
 * Remove consecutive slashes `//////dir/////` -> `/dir/`
 * Remove unnecessary self references `/dir/.` -> `/dir/.`
 * Possibly more
- Add some auxiliary functions like splitting to pathname and basename `/foor/bar` -> `/foo/`, `bar`
- Add path caching to speed up searches

**Comment by cahirwpz** [comment]
Will reopen as new _issue_ with more detailed information.
