### ISSUE TITLE
Utilize more CircleCI features

### ISSUE THREAD

**Issue by rafalcieslak** [cahirwpz/mimiker#378]
- Consider using a custom docker image with all tools pre-installed
- Consider caching downloaded files
- Store failed test log as an artifact
- Split configuration into jobs (separate jobs for compiling, format verification, pep8 verification and running kernel tests)
- Utilize all 4 containers to either increase the total number of seeds tested or to decrease the time to test results.

**Comment by cahirwpz** [comment]
Implemented with #381
