### ISSUE TITLE
Non-sleepable lock queues

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/mimiker#38]
Develop a mechanism that will have similar responsibility to FreeBSD's turnstiles described in the book. For reference look at: [sleepqueue.h](http://fxr.watson.org/fxr/source/sys/turnstile.h) and [subr_turnstile.c](http://fxr.watson.org/fxr/source/kern/subr_turnstile.c).

> Implementation of turnstiles is used to hold queue of threads blocked on non-sleepable locks. 
> Sleepable locks use condition variables to implement their queues. Turnstiles differ from a sleep
> queue in that turnstile queue's are assigned to a lock held by an owning thread.  Thus, when one
> thread is enqueued onto a turnstile, it can lend its priority to the owning thread.

**Comment by coodie** [comment]
Closed by #122
