### ISSUE TITLE
Sleep queues

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/mimiker#40]
Develop a mechanism that will have similar responsibility to FreeBSD's [sleepqueue](https://www.freebsd.org/cgi/man.cgi?query=sleepqueue&sektion=9). For reference look at: [sleepqueue.h](http://fxr.watson.org/fxr/source/sys/sleepqueue.h) and [subr_sleepqueue.h](http://fxr.watson.org/fxr/source/kern/subr_sleepqueue.c).

> Sleep queues provide a mechanism for suspending execution of a thread until some condition is met.  Each queue is associated with a specific wait channel when it is active, and only one queue may be associated with a wait channel at any given point in time.

**Comment by cahirwpz** [comment]
Please use [include/sleepq.h](https://github.com/cahirwpz/mimiker/blob/master/include/sleepq.h) as a starting point, please.

**Comment by Darge** [comment]
How will we keep the pointer to the current thread structure?
Linux calculates its address using the stack pointer: [link](http://stackoverflow.com/questions/12193281/how-does-the-kernel-know-what-is-the-current-thread).

**Comment by cahirwpz** [comment]
Your changes were merged after minor fixes with master. Nonetheless development of sleep queues must continue as the module is incomplete. Thanks for your work!
