### ISSUE TITLE
Need extra treatment of exceptions in branch delay slots.

### ISSUE THREAD

**Issue by mzr** [cahirwpz/mimiker#424]
When exceptions occur in a branch delay slot, we need to return from exception handler either to instruction after faulting instruction (branch not taken), or to branch target instruction (branch taken).

In case of branch taken our code doesn't follow the branch.
We need something like http://bxr.su/FreeBSD/sys/mips/mips/trap.c#MipsEmulateBranch.

I've already implemented test for this behaviour #419.

**Comment by cahirwpz** [comment]
Since we're going to drop support for MIPS architecture in the foreseeable future I don't think implementing this feature is desired anymore.
