### ISSUE TITLE
Outdated version of clang-format

### ISSUE THREAD

**Issue by wmoczulsky** [cahirwpz/mimiker#433]
Clang-format 3.8 is not available in official repository of Ubuntu 18.04. 

We can move to the newest stable version - 6.0. It is default version in the newest Ubuntu and Arch. Also it has backports to Debian stable and PPA for older Ubuntu versions. 

New formatting would change about 100 lines of code in 17 files.

**Comment by wmoczulsky** [comment]
Also we can use command `clang-format-6.0` instead of `clang-format` in Makefile in order to avoid mistakes.

**Comment by cahirwpz** [comment]
Fixed by #470
