### ISSUE TITLE
Assertion in ringbuf.c:11 fails.

### ISSUE THREAD

**Issue by dingorth** [cahirwpz/mimiker#453]
`assert(buf->count + bytes <= buf->size)` in `static void produce(ringbuf_t *buf, unsigned bytes)` fails.
In order to reproduce this bug one has to `./launch -g init=/bin/mandelbrot` and wait a few seconds.

**Comment by dingorth** [comment]
Maybe https://github.com/cahirwpz/mimiker/commit/cdee5a99a234711e64cde6e76b7f4a0fb7dcbe76 has something to do with it.

**Comment by cahirwpz** [comment]
Fixed in #442 but not yet commited.
