### ISSUE TITLE
Move data from malta.h to malta.dts

### ISSUE THREAD

**Issue by mzr** [cahirwpz/mimiker#508]
Since we can handle FDT, we should probably move machine description from include/mips/malta.h to malta.dts

**Comment by mzr** [comment]
#530 and #531 are merged!

**Comment by mzr** [comment]
We could use memresv block in device tree to specify reserved address ranges.
[DOC](https://elinux.org/images/c/cf/Power_ePAPR_APPROVED_v1.1.pdf)

**Comment by cahirwpz** [comment]
We're not going to invest more time into Malta board. We're planning to cease support for MIPS architecture in the near future.
