### ISSUE TITLE
Review signal handling routines and add missing functionality

### ISSUE THREAD

**Issue by cahirwpz** [cahirwpz/mimiker#567]
[signal(7)](https://netbsd.gw.com/cgi-bin/man-cgi?signal+7) implementation in described in great detail in chapter 4.7 of _"The Design and Implementation of FreeBSD Operating System"_. We know that our implementation of signals is very rudimentary.

We care mainly about following system calls:
* [sigaction](https://netbsd.gw.com/cgi-bin/man-cgi?sigaction)
* `sigreturn`
* [sigaltstack](https://netbsd.gw.com/cgi-bin/man-cgi?sigaltstack)
* [sigprocmask](https://netbsd.gw.com/cgi-bin/man-cgi?sigprocmask)
* [sigsuspend](https://netbsd.gw.com/cgi-bin/man-cgi?sigsuspend)

`ksh` makes heavy use of `sigprocmask`, `sigsuspend` and `sigaction`. There're also important users of these syscalls in _libc_.

* [x] remove `sa_restorer` from `struct sigaction` (kernel should inject `sigcode` that calls `sigreturn` onto userspace stack)
* [x] block signal that is being handled
* [x] support for `sigaction.sa_mask` (used in `ksh`)
* [x] minimal support for `sigaction.sa_flags` (~~`SA_INTERRUPT` for `ksh`~~ and `SA_RESTART` for `find`)
* [x] handle `SIGQUIT`, `SIGHUP`
* [x] handle `SIGTSTP`, `SIGTTIN`, `SIGTTOU`
* [x] handle `SIGCONT`
* [x] handle `SIGPIPE`
* [ ] handle `SIGTRAP` (and introduce `break 0` into `sigcode`)

IIRC we don't handle `siginfo_t *` argument of `sa_sigaction` at all.

**Comment by j-piecuch** [comment]
`SA_INTERRUPT` isn't defined in POSIX because the default behavior of signals is to interrupt system calls. Under SunOS, system calls were automatically restarted, and this flag disabled that behavior: https://www.tldp.org/LDP/lpg/node140.html

**Comment by cahirwpz** [comment]
You're right – `SA_INTERRUPT` is not even defined in _NetBSD_ or _FreeBSD_ header files.

**Comment by cahirwpz** [comment]
Since @j-piecuch implemented most of the features I consider this issue eligible for closure.
