### ISSUE TITLE
Kernel panic in ksh pipes when nonexistent command is used

### ISSUE THREAD

**Issue by jpszczolowski** [cahirwpz/mimiker#594]
1. Run `/bin/ksh`
2. Enter `nonexistent_command | wc`
3. Boom! Kernel panic
```
KERNEL PANIC!!!
TLB exception (load or instruction fetch) at $c0115774!
Caused by reference to $000000f4!
HINT: Type 'info line *0xc0115774' into gdb to find faulty code line.
```

**Comment by jpszczolowski** [comment]
@JakubSzczerbinski you may be interested in this

**Comment by cahirwpz** [comment]
Seems like there's an attempt to deliver a signal to a zombie process that still resides in a group created by `ksh`.
